on: [pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    container: zeronethunter/task1
    steps:
      - uses: actions/checkout@v2
      - run: make check
  test:
    runs-on: ubuntu-latest
    container: zeronethunter/task1
    steps:
      - uses: actions/checkout@v2
      - run: make test
  valgrind:
    runs-on: ubuntu-latest
    container: zeronethunter/task1
    steps:
      - uses: actions/checkout@v2
      - run: make valgrind
  coverage:
    runs-on: ubuntu-latest
    container: zeronethunter/task1
    needs: [ test ]
    steps:
      - uses: actions/checkout@v2
      - run: make coverage
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: build/report